sonata_admin:
    title: 'LiveGene'
    title_logo: '/bundles/sonataadmin/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
        handler: sonata.admin.security.handler.voter

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
