sonata_media:
    db_driver: doctrine_orm
    default_context: default
    admin_format: { width: 64, quality: ~, format: ~ }
    contexts:
        default:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                # - sonata.media.provider.dailymotion
                # - sonata.media.provider.youtube
                # - sonata.media.provider.image
                - sonata.media.provider.file
                # - sonata.media.provider.vimeo

            formats:
                admin: { width: 64, quality: 70, format: png }

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false

    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia

